# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 340)
        Dialog.setMinimumSize(QtCore.QSize(400, 340))
        Dialog.setMaximumSize(QtCore.QSize(400, 340))
        Dialog.setStyleSheet("QPushButton#upload_btn{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#upload_btn:pressed{\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#upload_btn{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#save_btn:pressed{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QDialog{\n"
"background-color: rgb(208, 235, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(136, 216, 255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"upload_btn{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.handle_btn = QtWidgets.QPushButton(Dialog)
        self.handle_btn.setEnabled(False)
        self.handle_btn.setGeometry(QtCore.QRect(70, 72, 111, 51))
        self.handle_btn.setObjectName("handle_btn")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.label_name.setObjectName("label_name")
        self.label_category = QtWidgets.QLabel(Dialog)
        self.label_category.setGeometry(QtCore.QRect(20, 200, 71, 16))
        self.label_category.setObjectName("label_category")
        self.label_company = QtWidgets.QLabel(Dialog)
        self.label_company.setGeometry(QtCore.QRect(20, 240, 121, 20))
        self.label_company.setObjectName("label_company")
        self.recipient_line = QtWidgets.QLineEdit(Dialog)
        self.recipient_line.setEnabled(False)
        self.recipient_line.setGeometry(QtCore.QRect(200, 160, 131, 20))
        self.recipient_line.setObjectName("recipient_line")
        self.company_line = QtWidgets.QLineEdit(Dialog)
        self.company_line.setEnabled(False)
        self.company_line.setGeometry(QtCore.QRect(200, 240, 131, 20))
        self.company_line.setObjectName("company_line")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setEnabled(False)
        self.save_btn.setGeometry(QtCore.QRect(50, 290, 271, 41))
        self.save_btn.setObjectName("save_btn")
        self.label_picture = QtWidgets.QLabel(Dialog)
        self.label_picture.setGeometry(QtCore.QRect(286, 23, 81, 51))
        self.label_picture.setText("")
        self.label_picture.setObjectName("label_picture")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(210, 100, 161, 21))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.label_tegs_error = QtWidgets.QLabel(Dialog)
        self.label_tegs_error.setGeometry(QtCore.QRect(116, 270, 171, 20))
        self.label_tegs_error.setText("")
        self.label_tegs_error.setObjectName("label_tegs_error")
        self.category_cb = QtWidgets.QComboBox(Dialog)
        self.category_cb.setEnabled(False)
        self.category_cb.setGeometry(QtCore.QRect(200, 200, 131, 22))
        self.category_cb.setObjectName("category_cb")
        self.category_cb.addItem("")
        self.category_cb.addItem("")
        self.category_cb.addItem("")
        self.upload_btn = QtWidgets.QPushButton(Dialog)
        self.upload_btn.setGeometry(QtCore.QRect(80, 20, 101, 24))
        self.upload_btn.setStyleSheet("`")
        self.upload_btn.setObjectName("upload_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.handle_btn.setText(_translate("Dialog", "Обработать"))
        self.label_name.setText(_translate("Dialog", "Получатель"))
        self.label_category.setText(_translate("Dialog", "Категория"))
        self.label_company.setText(_translate("Dialog", "Компания отправитель"))
        self.save_btn.setText(_translate("Dialog", "Сохранить письмо"))
        self.category_cb.setItemText(0, _translate("Dialog", "Без категории"))
        self.category_cb.setItemText(1, _translate("Dialog", "Срочно"))
        self.category_cb.setItemText(2, _translate("Dialog", "Спам"))
        self.upload_btn.setText(_translate("Dialog", "Загрузить файл"))
