# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(136, 206, 235);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLabel{\n"
" font: 30pt/30pt fantasy;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addmail_btn = QtWidgets.QPushButton(self.centralwidget)
        self.addmail_btn.setGeometry(QtCore.QRect(80, 160, 141, 51))
        self.addmail_btn.setObjectName("addmail_btn")
        self.seemail_btn = QtWidgets.QPushButton(self.centralwidget)
        self.seemail_btn.setGeometry(QtCore.QRect(80, 220, 141, 51))
        self.seemail_btn.setObjectName("seemail_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 131))
        self.frame.setStyleSheet("background-color: rgb(136, 206, 235);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_lbl = QtWidgets.QLabel(self.frame)
        self.name_lbl.setGeometry(QtCore.QRect(80, 30, 191, 61))
        self.name_lbl.setObjectName("name_lbl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MHelper"))
        self.addmail_btn.setText(_translate("MainWindow", "Добавить письмо"))
        self.seemail_btn.setText(_translate("MainWindow", "Мои письма"))
        self.name_lbl.setText(_translate("MainWindow", "MHelper"))
