# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'see_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(948, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setStyleSheet("QMainWindow{\n"
"background-color: rgb(208, 235, 255);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(136, 206, 235);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(136, 206, 235);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#find_btn{\n"
"background-color: rgb(136, 206, 235);\n"
"border: 2px solid rgb(136, 206, 235);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#find_btn:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#find_btn:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.see_btn = QtWidgets.QPushButton(self.centralwidget)
        self.see_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.see_btn.sizePolicy().hasHeightForWidth())
        self.see_btn.setSizePolicy(sizePolicy)
        self.see_btn.setMinimumSize(QtCore.QSize(75, 23))
        self.see_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.see_btn.setObjectName("see_btn")
        self.gridLayout.addWidget(self.see_btn, 0, 0, 1, 1)
        self.del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_btn.sizePolicy().hasHeightForWidth())
        self.del_btn.setSizePolicy(sizePolicy)
        self.del_btn.setMinimumSize(QtCore.QSize(75, 23))
        self.del_btn.setMaximumSize(QtCore.QSize(75, 23))
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 5, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sender_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sender_line.sizePolicy().hasHeightForWidth())
        self.sender_line.setSizePolicy(sizePolicy)
        self.sender_line.setMinimumSize(QtCore.QSize(113, 20))
        self.sender_line.setMaximumSize(QtCore.QSize(113, 20))
        self.sender_line.setObjectName("sender_line")
        self.gridLayout_2.addWidget(self.sender_line, 1, 0, 1, 1)
        self.sender_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sender_label.sizePolicy().hasHeightForWidth())
        self.sender_label.setSizePolicy(sizePolicy)
        self.sender_label.setMinimumSize(QtCore.QSize(81, 15))
        self.sender_label.setMaximumSize(QtCore.QSize(140, 16))
        self.sender_label.setObjectName("sender_label")
        self.gridLayout_2.addWidget(self.sender_label, 0, 0, 1, 1)
        self.recipient_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recipient_line.sizePolicy().hasHeightForWidth())
        self.recipient_line.setSizePolicy(sizePolicy)
        self.recipient_line.setMinimumSize(QtCore.QSize(113, 20))
        self.recipient_line.setMaximumSize(QtCore.QSize(113, 20))
        self.recipient_line.setObjectName("recipient_line")
        self.gridLayout_2.addWidget(self.recipient_line, 3, 0, 1, 1)
        self.find_btn = QtWidgets.QPushButton(self.centralwidget)
        self.find_btn.setMinimumSize(QtCore.QSize(113, 40))
        self.find_btn.setObjectName("find_btn")
        self.gridLayout_2.addWidget(self.find_btn, 5, 0, 1, 1)
        self.recipient_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recipient_label.sizePolicy().hasHeightForWidth())
        self.recipient_label.setSizePolicy(sizePolicy)
        self.recipient_label.setMinimumSize(QtCore.QSize(91, 20))
        self.recipient_label.setMaximumSize(QtCore.QSize(91, 20))
        self.recipient_label.setObjectName("recipient_label")
        self.gridLayout_2.addWidget(self.recipient_label, 2, 0, 1, 1)
        self.category_cb = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_cb.sizePolicy().hasHeightForWidth())
        self.category_cb.setSizePolicy(sizePolicy)
        self.category_cb.setMinimumSize(QtCore.QSize(111, 22))
        self.category_cb.setMaximumSize(QtCore.QSize(111, 22))
        self.category_cb.setObjectName("category_cb")
        self.category_cb.addItem("")
        self.category_cb.addItem("")
        self.category_cb.addItem("")
        self.category_cb.addItem("")
        self.gridLayout_2.addWidget(self.category_cb, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 948, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Окно просмтора"))
        self.see_btn.setText(_translate("mainWindow", "Смотреть"))
        self.del_btn.setText(_translate("mainWindow", "Удалить"))
        self.sender_label.setText(_translate("mainWindow", "  Компания отправитель"))
        self.find_btn.setText(_translate("mainWindow", "Поиск"))
        self.recipient_label.setText(_translate("mainWindow", "   Получатель"))
        self.category_cb.setItemText(0, _translate("mainWindow", "Все"))
        self.category_cb.setItemText(1, _translate("mainWindow", "Без категории"))
        self.category_cb.setItemText(2, _translate("mainWindow", "Срочно"))
        self.category_cb.setItemText(3, _translate("mainWindow", "Спам"))
